sass:
  sass_dir: _sass

title: Moera
tagline: Decentralized Social Network
github_username: MoeraOrg
tryit_link: false
card_overview_link: /overview/index.html
card_development_link: false
card_license_link: /license.html
